from datetime import datetime

from server.common.MeetingEntry import MeetingEntry
from tdoc.utils import GenericTdoc

class MeetingConfig:
    # Whether you want to pre-filter a specific group in the meetings GUI
    meeting_list_group_filter: str | None = None

    # Meetings not pertaining to a specific WG
    additional_meetings = [
        MeetingEntry(
            meeting_group="SP",
            meeting_number="1",
            meeting_url_3gu="https://portal.3gpp.org/Home.aspx#/meeting?MtgId=60806",
            meeting_name="3GPP WS on 6G",
            meeting_location="Incheon, KR",
            meeting_url_invitation="https://www.3gpp.org/ftp/workshop/2025-03-10_3GPP_6G_WS/Invitation/",
            start_date=datetime.fromisoformat('2025-03-10'),
            meeting_url_agenda="https://ftp.3gpp.org/workshop/2025-03-10_3GPP_6G_WS/Agenda/",
            end_date=datetime.fromisoformat('2025-03-11'),
            meeting_url_report="https://www.3gpp.org/ftp/workshop/2025-03-10_3GPP_6G_WS/Report/",
            tdoc_start=GenericTdoc("6GWS-250001"),
            tdoc_end=GenericTdoc("6GWS-250243"),
            meeting_url_docs="https://www.3gpp.org/ftp/workshop/2025-03-10_3GPP_6G_WS/Docs/",
            meeting_folder_url="https://www.3gpp.org/ftp/workshop/2025-03-10_3GPP_6G_WS/"),
        MeetingEntry(
            meeting_group="RP",
            meeting_number="1",
            meeting_url_3gu="https://portal.3gpp.org/Home.aspx#/meeting?MtgId=60517",
            meeting_name="RAN R19 WS",
            meeting_location="Taipei, TW",
            meeting_url_invitation="https://ftp.3gpp.org/TSG_RAN/TSG_RAN/TSGR_AHs/2023_06_RAN_Rel19_WS/Invitation/",
            start_date=datetime.fromisoformat('2023-06-15'),
            meeting_url_agenda="https://ftp.3gpp.org/TSG_RAN/TSG_RAN/TSGR_AHs/2023_06_RAN_Rel19_WS/Agenda/",
            end_date=datetime.fromisoformat('2023-06-16'),
            meeting_url_report="https://ftp.3gpp.org/TSG_RAN/TSG_RAN/TSGR_AHs/2023_06_RAN_Rel19_WS/Report/",
            tdoc_start=GenericTdoc("RWS-230001"),
            tdoc_end=GenericTdoc("RWS-230491"),
            meeting_url_docs="https://ftp.3gpp.org/TSG_RAN/TSG_RAN/TSGR_AHs/2023_06_RAN_Rel19_WS/Docs/",
            meeting_folder_url="https://ftp.3gpp.org/TSG_RAN/TSG_RAN/TSGR_AHs/2023_06_RAN_Rel19_WS/"),
        MeetingEntry(
            meeting_group="SP",
            meeting_number="1",
            meeting_url_3gu="https://portal.3gpp.org/Home.aspx#/meeting?MtgId=60539",
            meeting_name="SA R19 WS",
            meeting_location="Taipei, TW",
            meeting_url_invitation="https://www.3gpp.org/ftp/tsg_sa/TSG_SA/Workshops/2023-06-13_Rel-19_WorkShop/Invitation/",
            start_date=datetime.fromisoformat('2023-06-13'),
            meeting_url_agenda="https://www.3gpp.org/ftp/tsg_sa/TSG_SA/Workshops/2023-06-13_Rel-19_WorkShop/Agenda/",
            end_date=datetime.fromisoformat('2023-06-14'),
            meeting_url_report="https://www.3gpp.org/ftp/tsg_sa/TSG_SA/Workshops/2023-06-13_Rel-19_WorkShop/Report/",
            tdoc_start=GenericTdoc("SWS-230001"),
            tdoc_end=GenericTdoc("SWS-230088"),
            meeting_url_docs="https://www.3gpp.org/ftp/tsg_sa/TSG_SA/Workshops/2023-06-13_Rel-19_WorkShop/Docs/",
            meeting_folder_url="https://www.3gpp.org/ftp/tsg_sa/TSG_SA/Workshops/2023-06-13_Rel-19_WorkShop/"),
        MeetingEntry(
            meeting_group="SP",
            meeting_number="0",
            meeting_url_3gu="https://portal.3gpp.org/Home.aspx#/meeting?MtgId=82612",
            meeting_name="Spec Modernization #0",
            meeting_location="Online",
            meeting_url_invitation="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_00/Invitation/",
            start_date=datetime.fromisoformat('2025-07-03'),
            meeting_url_agenda="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_00/Agenda/",
            end_date=datetime.fromisoformat('2025-07-03'),
            meeting_url_report="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_00/Report/",
            tdoc_start=GenericTdoc("6GSM-250001"),
            tdoc_end=GenericTdoc("6GSM-250006"),
            meeting_url_docs="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_00/Docs/",
            meeting_folder_url="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_00/"),
        MeetingEntry(
            meeting_group="SP",
            meeting_number="1",
            meeting_url_3gu="https://portal.3gpp.org/Home.aspx#/meeting?MtgId=82613",
            meeting_name="Spec Modernization #1",
            meeting_location="Online",
            meeting_url_invitation="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_01/Invitation/",
            start_date=datetime.fromisoformat('2025-08-06'),
            meeting_url_agenda="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_01/Agenda/",
            end_date=datetime.fromisoformat('2025-08-06'),
            meeting_url_report="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_01/Report/",
            tdoc_start=GenericTdoc("6GSM-250007"),
            tdoc_end=GenericTdoc("6GSM-250050"),
            meeting_url_docs="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_01/Docs/",
            meeting_folder_url="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_01/"),
        MeetingEntry(
            meeting_group="SP",
            meeting_number="2",
            meeting_url_3gu="https://portal.3gpp.org/Home.aspx#/meeting?MtgId=82614",
            meeting_name="Spec Modernization #2",
            meeting_location="Online",
            meeting_url_invitation="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_02/Invitation/",
            start_date=datetime.fromisoformat('2025-09-03'),
            meeting_url_agenda="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_02/Agenda/",
            end_date=datetime.fromisoformat('2025-09-03'),
            meeting_url_report="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_02/Report/",
            tdoc_start=GenericTdoc("6GSM-250100"),
            tdoc_end=GenericTdoc("6GSM-250131"),
            meeting_url_docs="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_02/Docs/",
            meeting_folder_url="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_02/"),
        MeetingEntry(
            meeting_group="SP",
            meeting_number="3",
            meeting_url_3gu="https://portal.3gpp.org/Home.aspx#/meeting?MtgId=82635",
            meeting_name="Spec Modernization #3",
            meeting_location="Online",
            meeting_url_invitation="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_03/Invitation/",
            start_date=datetime.fromisoformat('2025-10-09'),
            meeting_url_agenda="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_03/Agenda/",
            end_date=datetime.fromisoformat('2025-10-09'),
            meeting_url_report="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_03/Report/",
            tdoc_start=GenericTdoc("6GSM-250201"),
            tdoc_end=GenericTdoc("6GSM-250234"),
            meeting_url_docs="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_03/Docs/",
            meeting_folder_url="https://ftp.3gpp.org/workshop/FS_6GSpecs/6GSM_Meeting_03/")
    ]
