import os
import tkinter

current_folder = os.path.dirname(os.path.realpath(__file__))

print(f'Loading generic table icons')
cloud_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'cloud.png'))
cloud_download_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'cloud_download.png'))
folder_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'folder.png'))
share_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'share.png'))
share_markdown_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'share_markdown.png'))
excel_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'excel.png'))
website_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'website.png'))
filter_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'filter.png'))
table_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'table.png'))
link_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'link.png'))
refresh_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'refresh.png'))
search_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'search.png'))
note_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'note.png'))
ftp_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'ftp.png'))
markdown_icon = tkinter.PhotoImage(file= os.path.join(current_folder, 'markdown.png'))
compare_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'compare.png'))
merge_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'merge.png'))
list_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'list.png'))
draft_icon = tkinter.PhotoImage(file=os.path.join(current_folder, 'draft.png'))